name: ruby-hack-assembler tests
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
      - name: Install dependencies
        run: gem install minitest
      - name: Run tests
        run: ruby -e 'ARGV.each { |f| require f }' ./test/*_test.rb
